### ISSUE TITLE
how can i load the MFSideMenu just in another ViewController ??? not in the rootViewController ???

### ISSUE THREAD

**Issue by marcelosantoro** [mikefrederick/MFSideMenu#101]
In AppDelegate i am doing it:
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
  {
  
   UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"MainStoryboard" bundle:[NSBundle mainBundle]];
  
  UIViewController *baseViewApp = [storyboard instantiateViewControllerWithIdentifier:@"MFSideMenuContainerViewController"];
  
  MFSideMenuContainerViewController *container = (MFSideMenuContainerViewController *)baseViewApp.view.window.rootViewController;
  
  UINavigationController *navigationController = [storyboard instantiateViewControllerWithIdentifier:@"navigationController"];
  
  UIViewController *leftSideMenuViewController = [storyboard instantiateViewControllerWithIdentifier:@"leftSideMenuViewController"];
  UIViewController *rightSideMenuViewController = [storyboard instantiateViewControllerWithIdentifier:@"rightSideMenuViewController"];
  
  [container setLeftMenuViewController:leftSideMenuViewController];
  [container setRightMenuViewController:rightSideMenuViewController];
  [container setCenterViewController:navigationController];

return YES;
}

This is my StoryBoard Identifier:
http://santoro.co/ios_deve.png

How can i do it ???

**Comment by mikefrederick** [comment]
Well, the MFSideMenuContainerViewController is your rootViewController. So it should be a parent of whatever view controller you are trying to access it from. Thus you could do something like this:

```
- (MFSideMenuContainerViewController *)menuContainerViewController {
    return (MFSideMenuContainerViewController *)self.parentViewController;
}
```

Or you could probably just get away with this:

```
[UIApplication sharedApplication].keyWindow.rootViewController
```

**Comment by misa1980** [comment]
Hi Mike,
i didn't understand, does that solve the problem and where to put these lines of code...
Thanks!
Regards!
