### ISSUE TITLE
UITableView swipe to delete issue

### ISSUE THREAD

**Issue by R1ckye** [mikefrederick/MFSideMenu#102]
My problem is I put 2 UITableViewControllers into an MFSideMenuViewController, a main view and a left view so nothing on the right.
Both of the UITableViewControllers have editing enabled but since the side menu handles all the pan gestures, it also handles the one what's supposed to reveal the delete button. It should only handle the ones which it needs so for example don't handle the right to left gesture when there isn't a view controller on the right and vice versa.

**Comment by mikefrederick** [comment]
I will think about this. Right now you could disable the menu's pan gestures when you are on that table.

To be fair, swipe to delete is a left-to-right motion, so this wouldn't really fix your problem.

**Comment by mikefrederick** [comment]
I am going to close this, since implementing it wouldn't actually fix the issue you are describing. Right now you would have to change the panMode to disable panning on the centerViewController, which should allow users to swipe your table view cells.

**Comment by veila** [comment]
i have met a same problem when push navigation a view and can not back by swipe to right. So in view which show menu i set MFSideMenuPanModeDefault, and in view which to back a normal way by swipe to right i set MFSideMenuPanModeNone and must to add code
self.navigationController.interactivePopGestureRecognizer.enabled = YES;
Only disable menu's pan is not enough.
i hope it can help u :)
