### ISSUE TITLE
Goto other view controller from current view controller

### ISSUE THREAD

**Issue by chinhnd** [mikefrederick/MFSideMenu#103]
HI all,

I'm using MFSideMenu in my app, it is too good, i also custom my app like facebook app. 

I add some quick bar button on navigation, when user click on it, it will show other view (As user click on menu and chose other item.). that is my problem, could anyone show me how to do that?

Many thanks

**Comment by mikefrederick** [comment]
You are going to have to give more details and be more clear about what your requirements are, I am really not sure what you are asking here.

**Comment by mikefrederick** [comment]
Closing this issue. I will open it back up if you provide more detail.
