### ISSUE TITLE
MFAppDelegate call function in DemoViewController? 

### ISSUE THREAD

**Issue by Troels-BH** [mikefrederick/MFSideMenu#104]
Hi

Im really happy to use your sidemenu in my project, but I have a question:

I want MFAppDelegate to call a function in the DemoViewController.
I have this was, but could not do it.
DemoViewController *demoViewController =  (DemoViewController *)[self sideMenu].navigationController.topViewController;

How do i do that?

**Comment by mikefrederick** [comment]
You would have had to initiated your demoViewController somewhere in your app delegate. You should be able to grab a reference to it when you initialize it.

You are using an older version of the library it looks like, I can't really help without knowing your setup. You might try giving more details and asking the question on StackOverflow.
