### ISSUE TITLE
Setting setRasterize = YES during rotation causes ill effects.

### ISSUE THREAD

**Issue by SamsonTwain** [mikefrederick/MFSideMenu#108]
I've found the problem is not consistent, but it appears that the center view controller gets pixelated after rotation.  In my case it was after video full screen animation.  I narrowed it down to your rotation implementation and use of setRasterize.  I added the following to your drawMenuShadows method correct the problem...

[self.centerViewController view].layer.rasterizationScale = [[UIScreen mainScreen] scale];

Similar problem here...

http://stackoverflow.com/questions/4475127/performance-scrolling-and-retina-resolution-images-in-calayer

Thanks for the nice work!

**Comment by mikefrederick** [comment]
Why did you add that code to the `drawMenuShadows` method? Was there logic behind that decision or did it just seem to fix your issue? It seems like `willAnimateRotationToInterfaceOrientation` or `didRotateFromInterfaceOrientation` might be better options (since that's where I toggle `shouldRasterize`).

**Comment by mikefrederick** [comment]
Also, are you able to consistently reproduce the issue? If so can you let me know how?

**Comment by SamsonTwain** [comment]
I decided to add it to drawMenuShadows, because the setting is determined by the device and the rotation methods would redundantly set the property.  It just seemed like a good fit, because it's a device setting.

I can repeat it, but I have to overlay MPMovieViewController while the app is rotating.  I haven't seen it in any other case, yet.  I could possibly get some example code together if you need it.  My guess is that if there is an animation or overlapping viewcontroller, while rotating the centerviewcontroller, the problem is present.

The overall process is...

1)  Added embedded video player to centerviewcontroller.
2)  On landscape rotation of app, send video player to full screen.
3)  On portrait rotation of app, send video player embedded in centerviewcontroller.
4)  Result...viewcontroller text and graphics are scaled down and blurry.

I hope this helps.  Let me know if you need anything.

**Comment by mikefrederick** [comment]
Example code would be appreciated, I haven't been able to replicate this yet.

**Comment by mikefrederick** [comment]
Could you possible fork the library and create an example using one of the demos?

**Comment by SamsonTwain** [comment]
Ok, Mike.  I have built a fork with an example application which uses video.  I believe it occurs after calling the UIDeviceOrientationDidChangeNotification notification (videoRotateFinish) and I think the video fullscreen animation is what triggers the problem.  Here are the steps...

1)  Run the MFSideMenuRasterizeFix application, making sure the emulator is using a retina screen.
2)  Touch the "Play" button.
3)  Wait for Bucky Bunny to start auto playing.
4)  Rotate to landscape, then back to portrait.  Full screen toggling will happen automatically with the orientation change.
5)  If you look at the Menu buttons and Seattle image, you will see pixelation.

I think the remedy is to add this line in your MFSideMenuShadow class, <B>show</B> method...

self.shadowedView.layer.rasterizationScale = [[UIScreen mainScreen] scale];

https://github.com/SamsonTwain/MFSideMenu

Please, let me know if I can help with anything else.  Thanks for the great lib.
