### ISSUE TITLE
Cannot continuously drag center view left and right. Locks to initial direction. 

### ISSUE THREAD

**Issue by ghost** [mikefrederick/MFSideMenu#109]
Basically you can't drag left a bit, then drag all the way to the right to reveal the menu (and vice-versa). Snapchat has the continuous center viewcontroller drag.

**Comment by mikefrederick** [comment]
I originally wrote it so that you could do this. I ended up following Facebook's implementation, which doesn't allow the continuous drag.

Would love to see a pull request making this optional.

**Comment by chourobin** [comment]
#114 has to be enabled by setting self.menuContainerViewController.elastic = YES;

**Comment by mikefrederick** [comment]
@chourobin I think you are misunderstanding this issue -- I believe what @ranuamar meant is that he wants to be able to drag from the right menu being open to the left menu being open all in one swipe.
