### ISSUE TITLE
Usage without ARC

### ISSUE THREAD

**Issue by ranses** [mikefrederick/MFSideMenu#116]
I just had a look at the podspec:
- s.requires_arc = true

Does this mean that i cannot run this library in my non ARC project?

I'm asking because i get a BAD_ACCESS error when i try to push the MFSideMenuContainerViewController with the standard UINavigationController pushViewController method (setting the Container as rootViewController does not fit for me).

Thanks!

**Comment by pkishino** [comment]
out of curiosity..why on earth would you still NOT be using arc?

**Comment by pkishino** [comment]
but yes, you can run it without arc as long as you add the arc compiler flag to the MFSideMenu files (check the readme :) )

**Comment by ranses** [comment]
cause i started this project when there was no ARC at all ;) i read that, but how can i add the compiler flag to the MFSideMenu files when i installed it through cocoapods? The files are not listed in the Build Phases - Compile sources...

**Comment by pkishino** [comment]
well, about time to convert the project then ;) weve recently started to convert a lot of out projects that were still using older non-arc externals.. its worth the time spent :)
anyways.. you are right, using podspecs I am not sure either where to set that ;/

**Comment by ranses** [comment]
okay, thanks anyway, i think i'll first convert the project into ARC :-)

**Comment by pkishino** [comment]
actually did a quick google and you could try this :+1: 
You can disable ARC-support by setting a compiler define. In a Podspec you would add this line:

s.compiler_flags = '-fobjc-arc'

**Comment by ranses** [comment]
ah okay, thx, i'll give it a try :)
