### ISSUE TITLE
Storyboard solution for login and out.

### ISSUE THREAD

**Issue by andylai** [mikefrederick/MFSideMenu#117]
Hi All,

I Am newbies in IOS development, looking for so many side menu library found that MFSideMenu quite OK, but facing the problem when integrate into my production application.

I am using Storyboard, and I want to do like this:
Login View Controller> Main View Controller(with MF side menu) > Logout

I see there is solution using dimiss the login view controller, but feel that not so good because in my application will go through some screen then only reach the main view controller that with MF Side Menu.

Appreciate any body can help, because unable found any solution....

Thanks.

**Comment by andylai** [comment]
the design will something like this 

![design](https://f.cloud.github.com/assets/5329185/1041546/fc49c004-0fd3-11e3-8f2c-34dbf7714005.png)

Thanks...

**Comment by mikefrederick** [comment]
You could read my comment on #118, which suggests some solutions to this.

I don't understand why you don't want to use a modalViewController. Can you explain this more clearly?
