### ISSUE TITLE
MFSideMenuContainerViewController NOT rootViewController

### ISSUE THREAD

**Issue by ranses** [mikefrederick/MFSideMenu#118]
I have an application that uses a type of login screen first before it starts with the main navigation hirarchy.

The problem is, when i try to push the whole MFSideMenuContainerViewController like an normal ViewController onto the view stack (after the login screen), i get unexpected behavior like white screens, displaced UI elements and so on...

Whats the usual way to use the MFSideMenu when you cannot set i as the rootViewController (cause of the Login Screen) ?

**Comment by mikefrederick** [comment]
You could make your login screen a modal view controller that lays over your MFSideMenuContainerViewController, which would allow you to still use the MFSideMenuContainerViewController as your root view controller.

Or you could put the login screen into the MFSideMenuContainerViewController and disable pan gestures on the MFSideMenuContainerViewController until the user has logged in. That way the user wouldn't be able to open the side menus while they were on the login screen.

**Comment by nneuberger1** [comment]
This is mostly a hacked at solution but worked.  I'm using a single storyboard, but I have a login page, and a secondary page prior to ever seeing the left navigation screens.

I modified the source code of MFSideMenuContainerViewController
- (void)awakeFromNib
  {
  
  UINavigationController *navigationController = [self.storyboard instantiateViewControllerWithIdentifier:@"navigationController"];
  UIViewController *leftSideMenuViewController = [self.storyboard instantiateViewControllerWithIdentifier:@"leftSideMenuViewController"];
  
  [self setLeftMenuViewController:leftSideMenuViewController];
  //    [container setRightMenuViewController:rightSideMenuViewController];
  [self setCenterViewController:navigationController];

}

I may try what @mikefrederick suggested with disabling the pan gestures next for a better solution.
