### ISSUE TITLE
Performance on rotation

### ISSUE THREAD

**Issue by cristibaluta** [mikefrederick/MFSideMenu#119]
Hi, are you aware of the fact that the rotation animation is not smooth at all? Are you going to fix it? You can see it even on the basic demo. Iphone 4 here.

**Comment by mikefrederick** [comment]
What do you mean by "not smooth"? No I am not aware of this. The library doesn't do much on rotation.

If you comment out these 3 methods in MFSideMenuContainerViewController is it smooth again?

```
shouldAutorotateToInterfaceOrientation:
willAnimateRotationToInterfaceOrientation:duration:
didRotateFromInterfaceOrientation:
```

**Comment by cristibaluta** [comment]
Well, not smooth means sluggish. Seems that comes from the shadow, if i comment only the last 2 methods works fine. I do not see any change in how the shadow works, so for my case i'm happy to just leave it commented.
