### ISSUE TITLE
Passing Data From SideMenu

### ISSUE THREAD

**Issue by xeravim** [mikefrederick/MFSideMenu#121]
Hi mike, I am facing a little bit issue with the new MFSideMenu. I need to pass data from my UITableViewController to an UINavigationController child. Here is the code

```
HotelListController *Hotel = [sb instantiateViewControllerWithIdentifier:@"HotelList"];
[Hotel setMyCoordinate:self.MyCoordinate];
NSArray *controllers = [NSArray arrayWithObject:Hotel];
navigationController.viewControllers = controllers;
[self.menuContainerViewController setMenuState:MFSideMenuStateClosed];
```

So that is my tought to pass data from the SideMenu, but it seems to be wrong, because it's crashing all the time. So how to pass data (MyCoordinate) to designated HotelListController? thanks!

**Comment by mikefrederick** [comment]
What line is causing it to crash? What is the exception?

**Comment by xeravim** [comment]
```
[Hotel setMyCoordinate:self.MyCoordinate];
```

that line.

**Comment by xeravim** [comment]
there is no exception, 0x17e3d85:  movl   16(%edx), %edx  EXC_BAD_ACCESS.

on the log just showing (lldb)

**Comment by xeravim** [comment]
ups sorry you can close this issue. I forgot to check whether self.MyCoordinate nil or not. Thanks Mike!
