### ISSUE TITLE
UIScrollView with paging not registering swipes

### ISSUE THREAD

**Issue by toxster** [mikefrederick/MFSideMenu#123]
Hi,

i have a LeftMenu, where i instantiate my views from storyboard as per the Demo Storyboard, i decided i want to have a UIViewController, with a UIView and on that i divide the screen in half width, and adding a UIScrollView with paging mode on the lower half. But the scrollview never gets any swipe gestures sent to it, i have disabled all panning on MFSideMenu, still no luck.

**Comment by mikefrederick** [comment]
Can you fork the project and alter the demo to mimick your situation? Then I can take a look and let you know how to handle the situation.

**Comment by toxster** [comment]
Please close this issue. After a long night i found that it is because of a change in ios 6 regarding the handling of AutoLayout and NSConstraints.

On 6 sep 2013, at 13:23, "Michael Frederick" <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you fork the project and alter the demo to mimick your situation? Then I can take a look and let you know how to handle the situation.

**Comment by tspike** [comment]
@toxster Could you please elaborate on your solution? I'm hitting something similar and thought MFSideMenu might have been what was causing it, but I'm intrigued to hear more.

**Comment by xeravim** [comment]
I believe that the scrollview gesture wouldn't work if you place it under viewDidLoad (autolayout on). It should under (void)viewDidAppear:(BOOL)animated. cheers!
