### ISSUE TITLE
Right menu and toolbar problems

### ISSUE THREAD

**Issue by cristibaluta** [mikefrederick/MFSideMenu#127]
Hi, i'm using MFSideMenu with a right controller. From the main controller i can push a photo gallery controller which has a toolbar (the rest of the app doesn't have a toolbar). Everything work as expected here, i can go back to the main controller and the toolbar disappears. The problem now is when i slide to left in order to show the right side menu, the toolbar appears but is not touchable, looks like someone made a screenshot of it and put it there. The toolbar moves along with the main controller, it's like is in the same view but outside it's bounds, however it is not because i gave some alpha to this view and the toolbar doesn't get the alpha. If i bring a modal view from the right menu, when i close it the toolbar is not there anymore. When the view of the photogallery disappears i set the items of the toolbar to nil, so the buttons shouldn't be there anymore. If i slide to see the left menu it doesn't happen. 
Do you have any idea why this happens? Not sure is related to the lib. Thanks.
![img_1171](https://f.cloud.github.com/assets/439123/1178566/ec264ab4-21b5-11e3-8ebf-33845fe265a6.PNG)

**Comment by mikefrederick** [comment]
It's hard for me to tell what's going on here. If you want to fork the project and adjust one of the demos to replicate this issue I can take a look.
