### ISSUE TITLE
ScrollsToTop disabled for CenterViewControllers

### ISSUE THREAD

**Issue by paulrolfe** [mikefrederick/MFSideMenu#130]
Has anyone else seen that MFSideMenu disables the scroll to top for tableviewcontrollers that are inside the container? Any way around that?

EDIT:
I believe it may be related to the fact that I put my leftsideview inside of a navigation controller to fix the iOS7 menubar issues.

**Comment by cnowacek** [comment]
I noticed that if I had a tableview in the left menu, the left menu tableview is the one that gets the "scrolls to top" message. I solved the issue by disabling scrollsToTop on the left menu's tableview.

**Comment by mikefrederick** [comment]
This shouldn't be an issue anymore.
