### ISSUE TITLE
interactivePopGestureRecognizer on iOS 7

### ISSUE THREAD

**Issue by nakul-kabra** [mikefrederick/MFSideMenu#134]
Is there any way in which i can keep the pan mode to Default and be able to swipe back when swiping back from the edge of the screen? For e.g. check the Foursquare App.

**Comment by nakul-kabra** [comment]
oh got it fixed!

**Comment by opr-sergey** [comment]
how fix this?

**Comment by SSGangwar** [comment]
How can i enable interactivePopGestureRecognizer with side menu, only on those classes where i didn't want to show side menu ?
