### ISSUE TITLE
Perform method on didSelectRow

### ISSUE THREAD

**Issue by codeFi** [mikefrederick/MFSideMenu#14]
I'm having issues calling a method from the mainView Controller in the sideMenu Controller (which is a UITableView) in didSelectRow.

Basically, I have a UIWebView in the mainView Controller which I want to scroll using
- (void) scrollToPosition
  {
  [_webView stringByEvaluatingJavaScriptFromString:@"window.scrollBy(0,400);"];
  DLog(@"Called");
  }

and I can't figure out how can I call this method in the sideMenu Controller in the didSelectRow without instantiating a new mainView (if I instantiate a new one the method is called but of course, it does nothing).

Thank you !

**Comment by mikefrederick** [comment]
stackoverflow would be a better place for this question
