### ISSUE TITLE
Rotation under iOS 5.1 - Need to implement older interface

### ISSUE THREAD

**Issue by dbleicher** [mikefrederick/MFSideMenu#140]
When building for iOS 5.1 (iPad) the app will not rotate to landscape with MFSlideMenu 0.5.4.  The file MFSideMenuContainerViewController.m properly overrides the "new" style method "-(BOOL)shouldAutorotate" but does not implement the older "-(BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation" method required by 5.x.  Overriding this older method fixes the issue.

Thanks!

**Comment by mikefrederick** [comment]
With this upcoming release of iOS 8 I don't intend on doing fixes for iOS 5.x anymore.
