### ISSUE TITLE
pass data to Side Menu - storyboards

### ISSUE THREAD

**Issue by abrantw73** [mikefrederick/MFSideMenu#141]
Can't seem to pass data to the Side Menu using Storyboards and listening for MFSideMenuStateEventMenuDidOpen.  Simply trying to set label on Side Menu.  No errors nor crash, just no data.  Brand new to iOS, and I apologize in advance if this is not the best place to post this.  See following code:
- (void)menuStateEventOccurred:(NSNotification *)notification {
  MFSideMenuStateEvent event = [[[notification userInfo] objectForKey:@"eventType"] intValue];
  
  if (event == MFSideMenuStateEventMenuWillOpen) {
      NSLog(@"Side Menu Opened");
      NSLog(@"CourseID: %@",_courseId);
  
  ```
  UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Main" bundle:[NSBundle mainBundle]];
  SideMenuViewController *rightSideMenuViewController = [storyboard instantiateViewControllerWithIdentifier:@"rightSideMenuViewController"];
  
  rightSideMenuViewController.courseIdLabel.text = _courseId;
  ```
  
   }
  }

**Comment by pkishino** [comment]
Hey,
It's been a while since I played with MFSideMenu but couldn't you just use segues? if you are already using storyboards you might as well take advantage of the tools.
that way you don't need to instantiate the controller and such, just pass along the data

**Comment by mikefrederick** [comment]
I am closing this because it has been a while and I am assuming you figured this out. Nothing in the library should prevent you from setting a property on a side menu.
