### ISSUE TITLE
prefersStatusBarHidden in leftMenuViewController

### ISSUE THREAD

**Issue by sethdeckard** [mikefrederick/MFSideMenu#142]
Hi,
Great control, I tried others and yours seemed to be the only one that properly handled supported orientations in the different child views.

I am running into one issue.  In my leftMenuViewController (which is just a UIViewController) I am overriding prefersStatusBarHidden to return YES so the status bar will be hidden in my side menu.

However it doesn't appear to be working and the prefersStatusBarHidden method is never called on my leftMenuViewController.

Any ideas?

**Comment by mikefrederick** [comment]
@sethdeckard are you trying to hide the status bar when the side menu appears? And have it appear again when the side menu closes? I am just trying to understand your use case right now.

**Comment by sethdeckard** [comment]
I ended up using a different controller instead (for different reasons) but if I try this one again I'll let you know if I run into the issue again.

**Comment by RishabhTayal** [comment]
Any updates on this thing? @mikefrederick I am trying to do what you described.

**Comment by sethdeckard** [comment]
Sorry for the late response but I did a search of my iOS projects and I don't seem to be using this library anywhere at this point. I'm going to close the issue since I'm unable to provide additional helpful feedback now.
