### ISSUE TITLE
How do i update table view of sidemenu?

### ISSUE THREAD

**Issue by GISmanimaran** [mikefrederick/MFSideMenu#148]
I have 10 menu options in my side menu. I want to change the image of button when the option is selected. How could i do that?

**Comment by MohanAprdc** [comment]
It is not clear to me. you have 10 menu options and when you select an option what should be updated?

**Comment by ghost** [comment]
@Manimaran12 On selection of an item in left menu, Are you trying to updating something in center view? or Do you want some button asset need to be updated in the Left menu itself?
Either way it should be simple, make use of delegates/blocks to updates the view accordingly.

**Comment by GISmanimaran** [comment]
@Krish33 @MohanAprdc  Thanks for your response. The issue was i want to update my table cell on selecting a cell from MFSideMenu. I founded solution for this. I just put this [tableview reloadData] on didSelectItemAtIndex method.

**Comment by mdhanu11** [comment]
Please tell me how can i use protocols or delegates in MFSidemenu

**Comment by mdhanu11** [comment]
Hi,

I have post a question regarding update labels in mfsidemenu in
stackoverflow. I did not get any reply from anyone. Could you please help
me.

Thanks
