### ISSUE TITLE
Failed to recognize gestures in tableviews

### ISSUE THREAD

**Issue by Bruno-Furtado** [mikefrederick/MFSideMenu#149]
Hello, 
I'm using `MFSideMenu` some time and noticed a possible bug that happens a few times. 

When a `UITableView`, or `UIScrollView` is displayed on the center screen, gesture recognition is lost. 

**Example:**
The user is in a central screen that has a `UITableView` and wants to scroll in this screen. The gesture opens, or try opens, the side menu.

Has anyone gone through this problem?
The failure occurs when using `UITableView` and `UIScrollView`.
My iOS deployment target is `6.0` and base SDK is `7.1`.

**Comment by luugiathuy** [comment]
@Bruno-Furtado: yes, I also encountered this problem. You can check my PR #146, it prevents side menus from opening when you scroll a tableview or scrollview.

**Comment by mikefrederick** [comment]
This should be fixed with my fix for #146.
