### ISSUE TITLE
Adding two menu (Left & Right ) to navigation controller

### ISSUE THREAD

**Issue by fsabri** [mikefrederick/MFSideMenu#15]
Hi ,

i have already modify the code in "MFSideMenuManager " to view the Left Table from view Controller instad of TableView using storyboard  

is there any way to add two Menu on the Left and Right with different View Controller from the same class , i'm trying to create new object from the "MFSideMenuManager " and changing the Methods property but i could not do it , i did not know where is the problem 

if you can help please

**Comment by mikefrederick** [comment]
You would have to get rid of the MFSideMenuManager sharedManager and adjust the code to use instances of MFSideMenuManager instead.

**Comment by fsabri** [comment]
Thank you for your post , i will try it
