### ISSUE TITLE
How to Logout from MFSlider.

### ISSUE THREAD

**Issue by subhashsa** [mikefrederick/MFSideMenu#150]
I am using the old version to display MFSideMenu.This following code i put in LoginviewController.

 SideMenuViewController *sideMenuViewController = [[SideMenuViewController alloc] init];         MenuOptions options = MenuButtonEnabled;
        [MFSideMenuManager configureWithNavigationController:delegate.nav
                                          sideMenuController:sideMenuViewController
                                                    menuSide:MenuLeftHandSide
                                                     options:options];
        ViewController *demoController =[[ViewController alloc] initWithNibName:@"ViewController" bundle:nil];
        [self.navigationController setNavigationBarHidden:NO];
        NSArray *controllers = [NSArray arrayWithObject:demoController];
        [MFSideMenuManager sharedManager].navigationController.viewControllers = controllers;
        [MFSideMenuManager sharedManager].navigationController.menuState = MFSideMenuStateHidden;

But i want to logout from MFslideMenu.Which code I can put in to the logout function.
I want to come back on LoginviewController .Please help me..

**Comment by ghost** [comment]
Perform Logout action on the left menu logout selection and once the logout is successful, do create a obj reference for LoginviewController and have it assigned to [MFSideMenuManager sharedManager].navigationController.viewControllers
Not sure about the old version code so its just an assumption this idea may work with older versions. You may also need to refine your left menu list as you are performing logout action.

**Comment by subhashsa** [comment]
Ok..Thanks

**Comment by nneuberger1** [comment]
I'm using this implemented in the SideMenuController.m didSelectRowAtIndexPath method.  This may help.

```
   [self.menuContainerViewController setMenuState:MFSideMenuStateClosed];
    UIViewController *vc = [[UIStoryboard storyboardWithName:@"MainStoryboard_iPhone" bundle:nil] instantiateViewControllerWithIdentifier:@"LoginViewControllerID"];

    [self.parentViewController presentViewController:vc animated:YES
          completion:^{
              NSLog(@"completed logout");

          }];

}
```
