### ISSUE TITLE
reason: '-[UINavigationController centerViewController]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by niravspaceo** [mikefrederick/MFSideMenu#151]
Hello,
When i push new view controller from SideMenuViewController(on tableviewdidselect method) , app crashes and the  reason: '-[UINavigationController centerViewController]: unrecognized selector sent to instance. I don't know how to deal with this.
Below is my code for push new controller 
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
  {
  UIViewController *demoController = [_arrayViewControllers   objectAtIndex:indexPath.row];
  UINavigationController *navigationController = self.menuContainerViewController.centerViewController;
    NSArray *controllers = [NSArray arrayWithObject:demoController];
    navigationController.viewControllers = controllers;
    [self.menuContainerViewController setMenuState:MFSideMenuStateClosed];
  }

Thanks,
Nirav

**Comment by ghost** [comment]
Typecast (UINavigationController*)self.menuContainerViewController.centerViewController, that may workout. 
But your crash says you are trying to access centerViewController with a navigational controller object instead of menuViewController. Double check the objects.

**Comment by mikefrederick** [comment]
@niravspaceo it seems you are calling `centerViewController` on a UINavigationController when you want to be calling it on your MFSideMenuContainerViewController.
