### ISSUE TITLE
iOS 7 status bat overlap

### ISSUE THREAD

**Issue by andwhy** [mikefrederick/MFSideMenu#153]
How can i disable status bar overlap like on ios 6?

self.edgesForExtendedLayout = UIRectEdgeNone;

**Comment by ghost** [comment]
I hope the only way is to design storyboard or Xib elements leaving top 20 pixels for status bar, No other go in iOS 7. Or if you are using Navigation bar it will align correctly beneath status bars.

**Comment by andwhy** [comment]
I add code below to SideMenuViewController and problem gone. 

[self.tableView setContentInset:UIEdgeInsetsMake(20, self.tableView.contentInset.left, self.tableView.contentInset.bottom, self.tableView.contentInset.right)];

i think you can add it to tips to your lib.

And thanks to this theme 
https://github.com/mikefrederick/MFSideMenu/issues/106

**Comment by HiveHicks** [comment]
I use UINavigationController as my center view controller, and everything's fine on iOS 7, but when running on iOS 6, navigation bar is partially hidden behind black status bar.

![image](https://cloud.githubusercontent.com/assets/1489247/2753212/a7804a58-c92c-11e3-8ece-275d2321f6d4.png)

How can I fix this?

**Comment by andwhy** [comment]
[self.tableView setContentInset:UIEdgeInsetsMake(20, self.tableView.contentInset.left, self.tableView.contentInset.bottom, self.tableView.contentInset.right)];
will help

**Comment by HiveHicks** [comment]
@andwhy it won't, because I don't have table view in my setup

**Comment by mikefrederick** [comment]
This should be fixed with the commit from #163.
