### ISSUE TITLE
How can i disable opening left OR right controller dynamically?

### ISSUE THREAD

**Issue by andwhy** [mikefrederick/MFSideMenu#154]
I can implement [_container setRightMenuViewController:nil]; but how can i do it in dynamic? Or maybe better disable pan recognizer for only one gesture(swipe right for example)? Can i do something in library bounds? Thanks

**Comment by andwhy** [comment]
I want to disable right slide on one screen and enable it on other

**Comment by mikefrederick** [comment]
@andwhy you can disable panning in `viewWillAppear`, and re-enable it in `viewWillDisappear`.

```
// enable panning on the center view controllers & the side menus (this is the default behavior):
menuContainerViewController.panMode = MFSideMenuPanModeCenterViewController | MFSideMenuPanModeSideMenu;

// disable all panning
menuContainerViewController.panMode = MFSideMenuPanModeNone;
```

**Comment by siggb** [comment]
For dynamically disabling opening check this Q/A: https://github.com/mikefrederick/MFSideMenu/issues/57
