### ISSUE TITLE
how can i update label content in sidemenu?

### ISSUE THREAD

**Issue by wilsoniPhone** [mikefrederick/MFSideMenu#155]
I change the table view side menu to my custom view.I have some labels in that view how can i update the label values in sidemenu when menu button is clicked.

**Comment by ghost** [comment]
Just have the Labels connected with IBOutlets or with IBOutletCollection, once done u can update them when the menu button is clicked. Make use of Protocols if required.

**Comment by wilsoniPhone** [comment]
i connected labels with IBOutlets but the label was not updated, delegate methods like viewDidload ,viewwillappear methods are also not called when menu button click or swipe pan.

**Comment by mdhanu11** [comment]
Hello Please reply on this guys. Even I need tha answer. PLease help me

**Comment by mikefrederick** [comment]
@wilsoniPhone @Dhanu11 this is not an issue with the library, please ask these questions on stackoverflow.
