### ISSUE TITLE
how to make sidemenu(either left or right) opaque

### ISSUE THREAD

**Issue by chandramouli952** [mikefrederick/MFSideMenu#156]
Hi,
    I'm using MFSidemenu for ios7 app,what happened is sidemenu is apperaing transparent how to make it opaque.I'm using tableViewController for sidemenu

**Comment by mikefrederick** [comment]
@chandramouli952 the demos have opaque side menus, you can check them out.

**Comment by MartienB** [comment]
@mikefrederick: Is this still the case? I cannot find a demo with opaque side menu's.
