### ISSUE TITLE
MFSidemenu problems using Dynamic data

### ISSUE THREAD

**Issue by niper007** [mikefrederick/MFSideMenu#158]
Hi I have a problem because I want to put dynamic data in my sidemenu, and I have to fix this quickly as I have a deadline coming up in a week.

I have created a [SideMenuViewController : UITableViewController] where I design and populate data in my sidemenu.

![screen shot 2014-05-14 at 13 00 44](https://cloud.githubusercontent.com/assets/2919992/2970153/0ca65cd8-db57-11e3-86ad-37864f7051bc.png)

When I start the app it shows all the data correctly, which I am getting from an API and storing in a mutable array. 

When I log in with another user, without closing the app. I receive the correct Data from the API, and the numberOfRowsInSection shows the correct amount.
![screen shot 2014-05-14 at 12 57 17](https://cloud.githubusercontent.com/assets/2919992/2970128/920a6d5c-db56-11e3-972a-29823f1f1ae1.png)

But when the app comes to cellForRowAtIndexPath it acts upon the old data that populated the mutable array before, and not the new data. Somehow it is saved, even thou I empty the mutable array, and now the sidemenu still shows the old data.
![screen shot 2014-05-14 at 12 48 32](https://cloud.githubusercontent.com/assets/2919992/2970028/57a00bbe-db55-11e3-8c2d-e68f4113bc5b.png)

I have trying reloading the tableview, but that doesn´t work. I made it call the viewdidload again, but that doesnt change anything. The only thing that makes the app show the correct data, is if I restart the app.
![screen shot 2014-05-14 at 12 51 07](https://cloud.githubusercontent.com/assets/2919992/2970056/af309d3a-db55-11e3-9e6d-b2e585748645.png)

So my question what can be wrong, is it possible to use dynamic data in the sidemenu, and if so what is the best way to achieve this?

**Comment by mikefrederick** [comment]
@niper007 nothing about the library should prevent you from reloading the data in the side menus. Since this is old I am closing it. If you find an actual bug with the library let me know.
