### ISSUE TITLE
How to show MFSlideMenu visible when went to DemoViewController

### ISSUE THREAD

**Issue by ghost** [mikefrederick/MFSideMenu#16]
How to show MFSlideMenu visible when went to DemoViewController. 

I'd like to show menu when first look.

I tried: 
[self.navigationController setMenuState:MFSideMenuStateHidden];

in viewDidLoad  of DemoViewController. but it not working.

**Comment by mikefrederick** [comment]
This is not an issue/bug, please post questions to stackoverflow.
