### ISSUE TITLE
using setCenterViewController in didSelectRowAtIndexPath is not working properly for landscape mode

### ISSUE THREAD

**Issue by trivikram619** [mikefrederick/MFSideMenu#164]
I want a tab view controller as the CentreViewController when one of the cell is selected. When i tried to change it programatically, it worked fine in portrait mode but in landscape mode, the right side menu is creating a white space after it is closed. That is the demo view controller still looks to be loading in the portrait mode (half of the screen). Could you please help me in resolving this issue. Or is there any other way of achieving what i required ?

**Comment by jerydarkside** [comment]
I had the same problem. I had to adapt a little the method in MFSideMenuContainerViewController, named - (void)setCenterViewController:(UIViewController *)centerViewController;

When it determines the frame, I added the check whether your are in portrait or landscape. The result is this :

 CGRect newFrame;
  UIDeviceOrientation orientation = [[UIDevice currentDevice] orientation];
  if (UIDeviceOrientationIsLandscape(orientation)) {
    newFrame = CGRectMake(origin.x, origin.y, centerViewController.view.frame.size.height, centerViewController.view.frame.size.width);
  } else {
    newFrame = CGRectMake(origin.x, origin.y, centerViewController.view.frame.size.width, centerViewController.view.frame.size.height);
  }
  [((UIViewController *)_centerViewController) view].frame = newFrame;

Hope it helps

**Comment by trivikram619** [comment]
Thanks a lot. It helped.
