### ISSUE TITLE
Only close rightViewController

### ISSUE THREAD

**Issue by serhatsezer** [mikefrederick/MFSideMenu#167]
Hey, 

I have two side menu leftMenuVC and rightMenuVC some specific area I want to do disable rightMenuVC but i did not find any solution. I just tried code below but it didn't work.

Here is my code snippet below 
https://gist.github.com/serhatsezer/0f4708b8d0bb76962900

**Comment by zephyr-dev** [comment]
@serhatsezer What do you mean by disable? If you want to make it so that the right side menu cannot be opened, you can just do:

```
[containerViewController setRightMenuViewController:nil];
```

**Comment by serhatsezer** [comment]
Thank you @zephyr-dev  solved my problem.

**Comment by zephyr-dev** [comment]
@serhatsezer whoops, it's mike, I am on the wrong account
