### ISSUE TITLE
Still have an problem disable rightMenuViewController

### ISSUE THREAD

**Issue by serhatsezer** [mikefrederick/MFSideMenu#168]
You said before I set to nil rightmenu like this [self.menuContainerViewController setRightMenuViewController:nil];

but I navigate to other page and I want to use "rightMenu" it isn't work. I tried to set disappear fuction but in vain! 
- (void)viewWillDisappear:(BOOL)animated
  {
  UIViewController *filterDrawMenuController = [self.mainStoryBoard instantiateViewControllerWithIdentifier:@"FilterDrawMenu"];
  [self.menuContainerViewController setRightMenuViewController:filterDrawMenuController];
  [super viewWillDisappear:animated];
  }

**Comment by mikefrederick** [comment]
@serhatsezer I can't provide much more help here without access to your project. Setting the rightMenuViewController to nil and then restoring it should be a simple way to disable/enable the right side menu.
