### ISSUE TITLE
How to make [MFSideMenuManager sharedManager]

### ISSUE THREAD

**Issue by poooyak** [mikefrederick/MFSideMenu#18]
I want to use MFSideMenu in my code.
When I wrote this line 

 if (controller != nil) {
        NSArray *controllers = [NSArray arrayWithObject:controller];
        [MFSideMenuManager sharedManager].navigationController.viewControllers = controllers;
    }
    [MFSideMenuManager sharedManager].navigationController.menuState = MFSideMenuStateHidden;

It said there is not declared.
What should I do ? 

And when I wrote : 
 if (controller != nil) {
        NSArray *controllers = [NSArray arrayWithObject:controller];
        self.sideMenu.navigationController.viewControllers = controllers;
    }
    self.sideMenu.menuState = MFSideMenuStateHidden;
It didn't work and menu didn't close after touch table cell

**Comment by mikefrederick** [comment]
Checkout the README and download the sample project, in version 0.3 I did a lot of refactoring of the library. 

Otherwise you can use version 0.2.
