### ISSUE TITLE
iOS 6.0 required?

### ISSUE THREAD

**Issue by yvbeek** [mikefrederick/MFSideMenu#19]
I've been playing around with the new version: 0.3

My app breaks In MFSideMenu.m - navigationControllerDidAppear on the line:
`[menuView setTranslatesAutoresizingMaskIntoConstraints:NO];`

It seems to be an iOS 6 only method.

Could you make the library iOS 5 (and higher) compatible?
Thanks

**Comment by AndyJordan** [comment]
iOS5 version  would be very useful.

Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: 'Could not instantiate class named NSLayoutConstraint'

NSLayout iOS6.

Thanks.

**Comment by kukosk** [comment]
I'm creating an app with MFSideMenu right now, and I would really appreciate if it can run on iOS5 as a lot of users uses it...

**Comment by mikefrederick** [comment]
There are issues with the sizing of the side menu when I don't use NSLayoutConstraint. If I figure it out I will surely add support for iOS5 again.

**Comment by bonui** [comment]
Comment these lines  (MFSideMenu.m near line 130 ) :

```
//[menuView setTranslatesAutoresizingMaskIntoConstraints:NO];
```

//   [containerView addConstraint:self.topConstraint];
  //  [containerView addConstraint:self.rightConstraint];
   // [containerView addConstraint:self.bottomConstraint];
    //[containerView addConstraint:self.leftConstraint];

Go to the XIB, in the first tab you just uncheck "Use autolayout"

That's it ! Work like a charm even in 4.3 :)

maybe you'll have problems with rotations or iPhone 5..

**Comment by OtaK** [comment]
I just removed the code that makes apps crash, iOS4.3+, no autolayout

Enjoy.

https://github.com/OtaK/MFSideMenu/tree/ios5

**Comment by yvbeek** [comment]
Thanks

**Comment by plaetzchen** [comment]
@OtaK There is a problem with your iOS5 branch on iOS6 devices: The SideMenu is hidden under the statusBar.

EDIT: I hot-fixed it with this in navigationControllerDidAppear in MFSideMenu.m:

<code>
float version = [[[UIDevice currentDevice] systemVersion] floatValue];
    if (version >= 6.0){
        [menuView setFrame:CGRectMake(menuView.frame.origin.x, menuView.frame.origin.y+19, menuView.frame.size.width, menuView.frame.size.height)];
    }
</code>

Is there a better way to do so?

**Comment by donobono** [comment]
thank you so much!!!
