### ISSUE TITLE
How to make the menu appear above the controller

### ISSUE THREAD

**Issue by freekmurze** [mikefrederick/MFSideMenu#21]
By default the menu appears underneath the detail controller. 
I'd like the menu appear above the detail controller. In other words when the user pulls the menu it should slide over the detail controller (example can be seen in The magazine app: https://itunes.apple.com/us/app/magazine-for-geeks-like-us./id557744510?mt=8). 
How can this be achieved?

**Comment by mikefrederick** [comment]
This would be a big change. I don't think that MFSideMenu is appropriate for this usage scenario. It's not what it was built for. I am not going to add support for this but feel free to fork and adjust to try to accomplish this.
