### ISSUE TITLE
Unregonized Selector running ios5

### ISSUE THREAD

**Issue by rmatesic** [mikefrederick/MFSideMenu#22]
When running on ios5 i receive this error

```
 [UIView setTranslatesAutoresizingMaskIntoConstraints:]: unrecognized selector sent to instance 0x46dc40'
```

I believe it is because it is trying to set constraints where in ios5 it doesn't support this. I was thinking to check if it is ios5 and use AutoresizingMask instead else ios6 will continue to you constraints. Would this be the best way to go?

**Comment by mikefrederick** [comment]
I will update the other issue pertaining to this so you should check back there:
https://github.com/mikefrederick/MFSideMenu/issues/19

**Comment by bonui** [comment]
Comment these lines  (MFSideMenu.m near line 130 ) :

```
//[menuView setTranslatesAutoresizingMaskIntoConstraints:NO];
```

//   [containerView addConstraint:self.topConstraint];
  //  [containerView addConstraint:self.rightConstraint];
   // [containerView addConstraint:self.bottomConstraint];
    //[containerView addConstraint:self.leftConstraint];

Go to the XIB, in the first tab you just uncheck "Use autolayout"

That's it ! Work like a charm even in 4.3 :)

maybe you'll have problems with rotations or iPhone 5..
