### ISSUE TITLE
Left & Right menus at the same time

### ISSUE THREAD

**Issue by pabloroca** [mikefrederick/MFSideMenu#23]
I tried to have left & right menus but it fails with some constraint

**Comment by mikefrederick** [comment]
With the release of the new facebook app this is something that I want to try to accomplish. Hopefully it can be integrated in the next version.

**Comment by montj2** [comment]
I am in the process of integrating this into a project and plan to have leftMenu and rightMenu and wanted some clarification - Does the OP mean having both displayed at the same time or just having a left and right menu? The later is what I'm very interested in helping with.

**Comment by mikefrederick** [comment]
Just having a left and right menu on the same navigation controller.

**Comment by mikenavarro** [comment]
I am looking for this same functionality. I was wondering if there was any progress?

**Comment by mikefrederick** [comment]
I did start this feature, but I haven't had much time to dedicate to the project recently. I am hoping to get to it soon.

**Comment by mikefrederick** [comment]
This feature has been added in the most recent version.

**Comment by pabloroca** [comment]
Cool ! Thanks
