### ISSUE TITLE
When adding a custom UITableView, the body pan mode does not work

### ISSUE THREAD

**Issue by mrbagels** [mikefrederick/MFSideMenu#24]
I have created my navigation controller with a root view controller of UIViewController. Basically a simple setup. When I programmatically create a UITableView and add it to the viewController, the swipe does not work in the body but only the navigation bar. If I dont add the tableview, it works perfectly with no issues. 

I have set the datasource and tableview delegate to self as well so everything is linked up. 

Not sure why it will not work with the table view added. I am using version 0.3

Thanks a lot!

**Comment by mikefrederick** [comment]
I disabled swipe for UITableViewCells since they frequently have swipe gestures associated with them and the swipe to reveal the side menu would over ride the swipe on the cells. I can see this was a stupid approach now because you can dynamically disable the menu's swipe gesture. I will change this in my next update.

**Comment by kylebegeman** [comment]
Out of curiosity is there any simple way to re-implement it? I imagine it might not be, and if so, any idea when a new update may come? 

I have a deadline in the next couple of weeks. Either I can keep it the way it is (the functionality for swiping is still there, its just only in the nav bar) and just add the updated MFSideMenu folder or I may have to revert to the previous version (where can I find the download for the previous version?)

Keep up the good work, this is an awesome feature! Thanks!

**Comment by d-a-n** [comment]
@kbegeman in MFSideMenu.m find

```
// we don't want to override UITableViewCell swipes
if ([touch.view isKindOfClass:[UITableViewCell class]] ||
    [touch.view.superview isKindOfClass:[UITableViewCell class]]) return NO;
```

and change the return value to YES.

**Comment by kylebegeman** [comment]
@d-a-n Thank you! I was poking around for awhile and I just didn't see this!

**Comment by mikefrederick** [comment]
This code has been removed from the project.
