### ISSUE TITLE
Modal Partial Curl with strange transparency effect

### ISSUE THREAD

**Issue by hobbsi** [mikefrederick/MFSideMenu#25]
Present a modal with the Partial Curl effect and it will be rendered incorrectly, with transparency where there should be some shadow effects.

Can be fixed by completely disabling shadow on MFSideMenu or be setting rootViewController.view.layer.shadowOpacity to 0.0f before presenting the modal...

**Comment by mikefrederick** [comment]
Interesting. Not really sure about a fix for this right now.

**Comment by mikefrederick** [comment]
This comes from https://github.com/mikefrederick/MFSideMenu/issues/38.

**Comment by mikefrederick** [comment]
Actually, I take that back, the culprit here is the fact that the rootViewController has a shadow. This doesn't seem to sit well with UIModalTransitionStylePartialCurl.

**Comment by mikefrederick** [comment]
For now the fix for this should be to disable the shadow on the menu as @hobbsi suggested. I will keep this issue in mind for the future incase I come up with a better solution.
