### ISSUE TITLE
how to enable MFSideMenu in a part of view area instead of full view screen?

### ISSUE THREAD

**Issue by tomsonxu** [mikefrederick/MFSideMenu#26]
I am using MFSideMenu, it looks great! Is it possible to just enable MFSideMenu for pan gesture in left 1/3 area of view instead of full view screen? Thanks.

**Comment by mikefrederick** [comment]
The library uses a UIPanGestureRecognizer for this. The relevant callback is `navigationControllerPanned` in `MFSideMenu.m`. You could fork the library and check the pan gesture's `locationInView:` to make sure that the pan occurred in the left 1/3 of the view.
