### ISSUE TITLE
Keyboard should be dismissed when tapping Menu button

### ISSUE THREAD

**Issue by FrancescoK** [mikefrederick/MFSideMenu#27]
For an example, see the demo project: Open sidebar menu, tap into the search field, tap on the menu button. Keyboard is still shown.

**Comment by mikefrederick** [comment]
I didn't put much effort into making the search bar work correctly as it isn't really part of the library. It was mostly just for show. But I will address this anyway.

**Comment by FrancescoK** [comment]
Makes sense - it's not a bug against the demo, I was thinking along the lines that tapping the menu button should always dismiss the keyboard... Else a WONTFIX is perfectly reasonable :)
