### ISSUE TITLE
Screen not rotating in iOS5

### ISSUE THREAD

**Issue by NickAchtienSavo** [mikefrederick/MFSideMenu#29]
Hi there,

I noticed that the orientation isn't rotating in iOS5.  I was able to fix it by by adding this in UINavigationController+MFSideMenu.m.  Though this is deprecated in iOS6, this still works and fixes the problem.

``` objectivec
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation
{
    return (toInterfaceOrientation != UIInterfaceOrientationPortraitUpsideDown);
}
```

**Comment by mikefrederick** [comment]
The rotation settings should not be in the library. You can put that code on your window's rootViewController, or if you are using a UINavigationController you can put it in your nav controller's root controller.
