### ISSUE TITLE
Remove lag

### ISSUE THREAD

**Issue by atnpem** [mikefrederick/MFSideMenu#3]
Hi, 

Can you add in your method (MFSideMenuManager.m) :

+(void) configureWithNavigationController:(UINavigationController *)controller sideMenuController:(id)menuController {
[...]
//ADD THIS LINE
controller.view.layer.shadowPath = [UIBezierPath bezierPathWithRect:controller.view.bounds].CGPath;
}

Thanks Vinicius Albino (comment on Cocoa Controls)

**Comment by mikefrederick** [comment]
Will do, thanks for the suggestion.
