### ISSUE TITLE
Can't scroll content in DemoViewController

### ISSUE THREAD

**Issue by kremens** [mikefrederick/MFSideMenu#30]
Hi,

Can't manage to scroll content vertically in DemoViewController. I've been wrestling with it for a bit, and it seems that the gesture recognizer is overriding the default behavior of UIScrollView.

Any ideas on how to address this?

**Comment by kremens** [comment]
Haha - never mind! User error...

Thanks for the great lib! Works very nicely :-)

**Comment by jpttsn** [comment]
C'mon, at least tell us how you solved it :)

It appears a Table View Controller set directly as the center view controller won't scroll, but one embeded in a Navigation View Controller will.
