### ISSUE TITLE
MFSideMenu should definitely use view controller containment

### ISSUE THREAD

**Issue by kukosk** [mikefrederick/MFSideMenu#31]
Hi.

Thanks for a great lib!
There is one thing that would (in my opinion) make MFSideMenu a lot better! It's view controller containment. Imagine a scenario in which you would use MFSideMenu as the main window's RootViewController, having two properties for the menuViewController and contentViewController. It could potentially fix Issue #19, too.

Thank you for such a good library again:)

**Comment by mikefrederick** [comment]
That's an interesting idea. I'll think it over.

**Comment by bonui** [comment]
It could potentially fix Issue #19, too.

No it won't ViewControllerContainer" are not enable in iOS 4

**Comment by mikefrederick** [comment]
When I created this library, I wanted it to be a "drop-in solution". The idea was to minimize the amount of refactoring needed to integrate the library in a project. I am not going to move towards a situation where the menu is the rootViewController of the window, but I might end up refactoring the relationships between controllers.
