### ISSUE TITLE
Mailcomposer overwriting in the slidemenu

### ISSUE THREAD

**Issue by sivasankarp** [mikefrederick/MFSideMenu#32]
Hi 

 its great component to use it,currently facing issue when i add the Mailcomposer in the slidemenu,It was overwriting in the same slidemenu.May i know how to make the composer to come out of the slide menu,
Even i have tried on the top of the Demoviewcontroller facing same problem.
Can you please guide me to fix this issue.

Thanks in advance.
![iOS Simulator Screen shot 10-Dec-2012 1.05.17 PM.png](https://f.cloud.github.com/assets/80171/3053/312e8ee0-429c-11e2-8107-78eb78305c92.png)

**Comment by mikefrederick** [comment]
What do you mean when you say "It was overwriting in the same slidemenu"?

Unless I am mistaken, this doesn't appear to be an issue with the library but rather a general question. If that's the case please ask the question on stackoverflow.

If you have actually found an issue with the project, please elaborate on it and we can reopen this issue.
