### ISSUE TITLE
Anyway to show complete view of the sideMenu?

### ISSUE THREAD

**Issue by zaikshev88** [mikefrederick/MFSideMenu#34]
As seen in the screenshot, I would like to be able to show the complete sidemenu during a search. Is there any way to do this?

![Screen Shot 2012-12-13 at 11 43 27 PM](https://f.cloud.github.com/assets/808970/10968/f4887cb0-453b-11e2-9e71-8ea301247af2.png)

**Comment by zaikshev88** [comment]
I tried to do this [self.sideMenuTableView.sideMenu setRootControllerOffset:320]; but it doesn't seem to work, anyone has any advise on this?

**Comment by mikefrederick** [comment]
In MFSideMenu.h you can change the kMFSideMenuSidebarWidth constant if you want to change how much of the menu should be shown.
