### ISSUE TITLE
How to disable pan mode for specific view controllers?

### ISSUE THREAD

**Issue by lconstable** [mikefrederick/MFSideMenu#37]
Great library!

I'm new to iOS development and have one quick question - how can we disable the pan mode for specific view controllers (i.e. so that the behavior of swiping will not present the side menu controller)? The only 2 pan modes I could find were for the navigation bar and for the navigation controller -- can we disable those in some way?

Thanks again for your hard work.

**Comment by mikefrederick** [comment]
You can do sideMenu.panMode = 0 in viewWillAppear and you can restore whatever other panMode you were using when the view disappears.

This is not an issue with the project. Please refrain from asking questions here. You can ask questions on StackOverflow.
