### ISSUE TITLE
MFSideMenu only for ios6???

### ISSUE THREAD

**Issue by jan-hoelscher-mss** [mikefrederick/MFSideMenu#40]
my project is running with deployment target of 5.0, 
which does not have Layout Constraints like ios 6.

It allways crash on devices with ios prior to ios6 with the following message.
'Could not instantiate class named NSLayoutConstraint'
which should be called on line MFSideMenu:177

could it be possible that you rewrite this for older ios prior version 6?

Regards,
Jan

**Comment by mikefrederick** [comment]
See https://github.com/mikefrederick/MFSideMenu/issues/19
