### ISSUE TITLE
Navigation button blinks when using with sotryboards

### ISSUE THREAD

**Issue by acduranjr** [mikefrederick/MFSideMenu#41]
The left navigation button blinks when using MFSideMenu with storyboard. Any suggestion to fix it?

**Comment by mikefrederick** [comment]
Can you elaborate? How can I reproduce this issue? I have used MFSideMenu with storyboards and I haven't seen this issue before.

**Comment by acduranjr** [comment]
I made some code changes but the issue exists without the changes. I create a navigation controller subclass instead using your category that overrides important methods.

The application starts with a navigation controller defined at storyboard. Than, side menu is created. I guess this is the blink reason. How do you use MFSideMenu with storyboard?

App Delegate

```
- (void)sideMenu {
    MFNavigationController *navigationController = (MFNavigationController *)[self.window rootViewController];
    MBOSideMenuViewController *sideMenuViewController = [navigationController.storyboard instantiateViewControllerWithIdentifier:@"Side Menu"];
    MFSideMenuOptions options = MFSideMenuOptionMenuButtonEnabled|MFSideMenuOptionBackButtonEnabled|MFSideMenuOptionShadowEnabled;
    MFSideMenuPanMode panMode = MFSideMenuPanModeNavigationBar|MFSideMenuPanModeNavigationController;
    MFSideMenu *sideMenu = [MFSideMenu menuWithNavigationController:navigationController sideMenuController:sideMenuViewController location:MFSideMenuLocationLeft options:options panMode:panMode];
    sideMenuViewController.sideMenu = sideMenu;
}
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    [self sideMenu];
    return YES;
}
```

**Comment by mikefrederick** [comment]
Well, if you are seeing an issue, you could just set the button in your `sideMenu` method... Something like this would work:
`myViewController.navigationItem.leftBarButtonItem = [sideMenu menuBarButtonItem];`
