### ISSUE TITLE
Autolayout problem with 5.1 release

### ISSUE THREAD

**Issue by lsantaniello** [mikefrederick/MFSideMenu#43]
Hi all, I use 5.1 and I have running problem. When I run ademo app I obtain this error:
'NSInvalidUnarchiveOperationException', reason: 'Could not instantiate class named NSLayoutConstraint'

If I disable Autolayout, app start but then crash whit other error:

2013-01-12 10:38:05.274 MFSideMenuDemo[875:c07] -[UITableView setTranslatesAutoresizingMaskIntoConstraints:]: unrecognized 

Can you help me?

Thanks

**Comment by EpicDraws** [comment]
+1

This appears to be a blocking issue for us as well.

**Comment by burakkilic** [comment]
+1

**Comment by EpicDraws** [comment]
Has anyone fixed or worked around this issue? We like the new features, but this is blocking release for us.

**Comment by bluesuedesw** [comment]
+1 Problem is that autolayout is not supported on iOS 5, so a fallback method for pre < iOS 6 devices would be in order (autoResizingMasks?)

**Comment by garudaonekh** [comment]
same issue here. This is bad. It should support 4.3 and above. I have to go back to its old version.

**Comment by mikefrederick** [comment]
Support for iOS 5 is added again in the newest commit.
