### ISSUE TITLE
How can i enable pan mode for sideMenuButton again?

### ISSUE THREAD

**Issue by laszlotuss** [mikefrederick/MFSideMenu#45]
Hy there,
I used an older version on MFSideMenu, but now i upgraded it to the latest and my sideMenuButton no longer use the pan effect.
Actually i don't really used gestureRecognizers and i really need any time to spend my own code.
Can someone help to reenable this option? Like forcing 
- (void) toggleSideMenuPressed:(id)sender To use the 
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch {
  maybe? I don't really know. Thank you

**Comment by jweyrich** [comment]
That's in my wish-list too. The button no longer responds to pan, which is sad :(
@mikefrederick do you have any hint for us?

**Comment by mikefrederick** [comment]
I just fixed this.
