### ISSUE TITLE
Menu pan shows empty controller

### ISSUE THREAD

**Issue by bddq** [mikefrederick/MFSideMenu#46]
Hi !
I have a problem. I've created an MFSideMenu with a nil right view controller but the gesture recognizer is still working and try to show the right menu. This right menu should not be shown if it's nil.

Can you test it the pan gesture recognizer ?

Thanks for everything.
Benoit

**Comment by NSMutableString** [comment]
+1 same here

**Comment by shir** [comment]
same for me

**Comment by mikefrederick** [comment]
Sorry guys, that was a really poor mistake, I am hoping to create some tests for the project soon. This is fixed now.

**Comment by shir** [comment]
Could you create new minor pod version with this fix?

**Comment by mikefrederick** [comment]
@shir there is now a 0.4.1 pod

**Comment by shir** [comment]
@mikefrederick Thank you!

**Comment by bddq** [comment]
Thanks !
