### ISSUE TITLE
Side menu frame is wrong

### ISSUE THREAD

**Issue by bddq** [mikefrederick/MFSideMenu#47]
Hi there,

When using a big table view inside a side menu controller, the frame of the menu controller is not fitting the app window frame.

How can we solve this ?
The bug occurs on both iOS 5/6.

Best regards,
Benoit

**Comment by bddq** [comment]
It seems that menuContainerView must be initialized with the appFrame.

`self.menuContainerView = [[UIView alloc] initWithFrame:[[UIApplication sharedApplication] delegate].window.screen.applicationFrame];`

**Comment by zephyr-dev** [comment]
Are you seeing this on the iPad or the iPhone? What does the frame of the menu controller look like??

**Comment by bddq** [comment]
I'm seeing this on the iPhone.
My menucontroller is twice as high (height 960).
I think it's because of its autoResizingMask and because the menuContainerView is not initialized with a frame.
When resizing the menuContainerView in -orientSideMenuFromStatusBar, the menuController adjusts (wrongly) its height...

Thanks.

**Comment by mikefrederick** [comment]
Is it possible for you to post a screenshot of this?

**Comment by bddq** [comment]
![iOS Simulator Screen shot 21 fe vr 2013 14 36 44](https://f.cloud.github.com/assets/342063/180302/e3c1d792-7c2b-11e2-96b5-6cf3062b7083.png)
Try to create a table view with 2 section with 10 rows. The table view cannot be entirely seen in the side bar...

**Comment by mikefrederick** [comment]
Ah shoot, I see. I just uploaded a fix for this issue. Should be all set now.
