### ISSUE TITLE
open left side all over

### ISSUE THREAD

**Issue by fabiosoft** [mikefrederick/MFSideMenu#48]
i have a seachbar into the tableheder of side left menu... now..my search bar is cutted in half because the main view is over the side.
How can i show the entire side menu only in certain events? Like facebook app does when you tap on search bar?

i am looking for a method for doing this...now i am using 
[self.navigationController.sideMenu setMenuState:MFSideMenuStateVisible];
for partially showing the menu table.

thanks

**Comment by mikefrederick** [comment]
As of the most recent version, you can change the menuWidth to accomplish this.
