### ISSUE TITLE
Can't get it working with Storyboards. 

### ISSUE THREAD

**Issue by Lukaz32** [mikefrederick/MFSideMenu#50]
Whats the correct way of implementing the menu using Storyboards?
I couldn't make it work with the older Issue about this topic.

**Comment by nicarq** [comment]
Same for me :-/

**Comment by iamlordvodemort** [comment]
I am having a problem adding an image to the titleView of the navigation view controller, where would i do this? i've tried in the appdelegate but no luck. can you help me with this?

**Comment by mikefrederick** [comment]
It is pretty straightforward, but I am working on getting some example code for storyboards into the project. For now, here is the basic setup:

``` objective-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"MainStoryboard" bundle:[NSBundle mainBundle]];
    UINavigationController *navigationController = (UINavigationController *)self.window.rootViewController;
    UIViewController *leftSideMenuViewController = [storyboard instantiateViewControllerWithIdentifier:@"leftSideMenuViewController"];
    MFSideMenu *sideMenu = [MFSideMenu menuWithNavigationController:navigationController
                                             leftSideMenuController:leftSideMenuViewController
                                            rightSideMenuController:nil];
    return YES;
}
```

**Comment by mikefrederick** [comment]
There is a storyboard demo available now.

**Comment by Lukaz32** [comment]
Thanks a lot! =D

**Comment by marcelosantoro** [comment]
@mikefrederick how can i load the MFSideMenu just in another ViewController ??? not in the rootViewController ???

i am trying it:
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
  {
      UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"MainStoryboard" bundle:[NSBundle mainBundle]];
  
   UIViewController *baseViewApp = [storyboard instantiateViewControllerWithIdentifier:@"MFSideMenuContainerViewController"];
  
   MFSideMenuContainerViewController *container = (MFSideMenuContainerViewController *)baseViewApp.view.window.rootViewController;
  
   UINavigationController *navigationController = [storyboard instantiateViewControllerWithIdentifier:@"navigationController"];
  
   UIViewController *leftSideMenuViewController = [storyboard instantiateViewControllerWithIdentifier:@"leftSideMenuViewController"];
   UIViewController *rightSideMenuViewController = [storyboard instantiateViewControllerWithIdentifier:@"rightSideMenuViewController"];
  
   [container setLeftMenuViewController:leftSideMenuViewController];
   [container setRightMenuViewController:rightSideMenuViewController];
   [container setCenterViewController:navigationController];
  return YES;
  }

But the MFSideMenu is not loading :(

can you help me.

Tks
