### ISSUE TITLE
Disable all gestures via option

### ISSUE THREAD

**Issue by NSMutableString** [mikefrederick/MFSideMenu#53]
It should be nice if the side menu can be disabled at a certain point by just calling a disable method on it. When it can be active again. We could call the enable method to activate it once again.

This could come in handy when you want to force your users through a wizard.

**Comment by mikefrederick** [comment]
You can do this like so:

`menu.panMode = 0;`

And to re-enable it:

`menu.panMode = MFSideMenuPanModeNavigationBar|MFSideMenuPanModeNavigationController;`
