### ISSUE TITLE
panning doesn't work correctly with one menu

### ISSUE THREAD

**Issue by russes** [mikefrederick/MFSideMenu#54]
If you implement MFSideMenu with only one side menu enabled, you'll find that panning doesn't work correctly.  If you look at MFSideMenu.m, you'll find this code fragment:
- (void) handleLeftPan:(UIPanGestureRecognizer *)recognizer {
  if(!self.rightSideMenuViewController) return;

If the rightSideMenuViewController is set to nil, the right side menu is locked out, which is the correct behavior.

However, if you've completely exposed the leftSideViewController, the if statement disables panning to the left, which makes the navigation controller appear to be locked into position on the far right.

The handleRightPan method has the same problem when leftSideViewController is set to nil.

You'll only see this problem under single menu implementations.

The fix is simple.  If you want it, let me know.

**Comment by marcllucia** [comment]
Same issue here

**Comment by russes** [comment]
The fix is simple:  in MFSideMenu.m, make this change:
- (void) handleLeftPan:(UIPanGestureRecognizer *)recognizer {
  //  if(!self.rightSideMenuViewController) return;
  
  UIView *view = self.rootViewController.view;
  
  CGPoint translatedPoint = [recognizer translationInView:view];
  CGPoint adjustedOrigin = [self pointAdjustedForInterfaceOrientation:panGestureOrigin];
  translatedPoint = CGPointMake(adjustedOrigin.x + translatedPoint.x,
                                adjustedOrigin.y + translatedPoint.y);
  
  translatedPoint.x = MAX(translatedPoint.x, -1*kMFSideMenuSidebarWidth);
  if(self.menuState == MFSideMenuStateLeftMenuOpen) {
      // don't let the pan go less than 0 if the menu is already open
      translatedPoint.x = MAX(translatedPoint.x, 0);
  } else {
      // we are opening the menu
      if(!self.rightSideMenuViewController) return;           // test for one menu implementation here
      translatedPoint.x = MIN(translatedPoint.x, 0);
  }

Note that the first line of the method is commented out.  Copy and enable that line to where the comment "test for one menu implementation here" is.  Do the same change for handleRightPan, while reversing right and left.

**Comment by marcllucia** [comment]
it works! :+1:
