### ISSUE TITLE
Disable Right Panning

### ISSUE THREAD

**Issue by marcllucia** [mikefrederick/MFSideMenu#57]
Is there anyway to disable the right panning even when draggin the screen to the left?

**Comment by mikefrederick** [comment]
Do you mean that you want to enable left panning but disable right panning? I am not sure what you mean. Can you explain your use case?

**Comment by marcllucia** [comment]
Yes that's what I want

**Comment by mikefrederick** [comment]
Can you explain your use case? I want to understand your situation better.

**Comment by marcllucia** [comment]
Ok, so I want to disable the event of dragging to the left but only when it shows the right SideMenu, I still want this event to return to the Home when the screen is panned to the left.

**Comment by mikefrederick** [comment]
You can change the panMode of the menu at any time to enable/disable panning

**Comment by erdemgc** [comment]
how can i disable swipe left and right to open the menu, just open menu with the bar buttons?

**Comment by luugiathuy** [comment]
hi @erdemgc, you can disable the menu swiping in a view controller by:

```
self.menuContainerViewController.panMode = MFSideMenuPanModeNone;
```

To open menus with bar buttons, you can use:

```
[self.menuContainerViewController toggleRightSideMenuCompletion:nil]; 
```

or

```
[self.menuContainerViewController toggleLeftSideMenuCompletion:nil];
```

in bar buttons' handler functions to manually open menus

**Comment by siggb** [comment]
Solution for disabling Right Panning without disabling Left Panning:

1) `@property (nonatomic, assign) BOOL shouldHandleLeftPan;`
2) `- (void) handleLeftPan:(UIPanGestureRecognizer *)recognizer
{
if (!self.shouldHandleLeftPan) return;
if(!self.rightMenuViewController && self.menuState == MFSideMenuStateClosed) return;` ...
3) on viewWillAppear/viewWillDisappear do something like this: `[self.menuContainerViewController setShouldHandleLeftPan:NO];`
4) Profit!
