### ISSUE TITLE
panning can overshoot the underlying menu in certain cases

### ISSUE THREAD

**Issue by russes** [mikefrederick/MFSideMenu#58]
If you pan the main view all the way to the right, the main view will lock against the right edge of the underlying menu.

Now, pan the main menu back to the left about a quarter inch.  Don't remove your finger from the screen.  Try panning the menu all the way to the right.  You should be able to overshoot the right edge of the underlying menu.  The main view will snap back into position once you remove your finger from the screen.

The main menu should lock into position on the right for both cases.

**Comment by mikefrederick** [comment]
Good catch, will issue a fix soon

**Comment by russes** [comment]
```
I may send you a pull request for the other issue I reported.  It's a simple patch & I need the practice walking through the steps.  Ignore it if you're already made the other change I gave you.
```

**Comment by mikefrederick** [comment]
This is fixed in the most recent version.
