### ISSUE TITLE
Displaying a modal view from the right menu changes the frame

### ISSUE THREAD

**Issue by miguelj** [mikefrederick/MFSideMenu#60]
This is a strange one. If you display a modal view while in the right menu and then dismiss it, the right menu view will be moved back to the left - i.e. its frame will change and it will have an origin of 0,0 instead of the origin that is offset by the kMFSideMenuSidebarWidth  and its width will be the full screen.
Before showing the modal view:
![iOS Simulator Screen shot Mar 19 2013 3 38 27 PM](https://f.cloud.github.com/assets/3910706/276078/b45bbd02-90a2-11e2-8e97-88fc22dfa9d6.png)

After dismissing the modal view:
![iOS Simulator Screen shot Mar 19 2013 3 38 33 PM](https://f.cloud.github.com/assets/3910706/276083/c0ff0faa-90a2-11e2-8984-6d9cf0135a93.png)

**Comment by mikefrederick** [comment]
What version are you using? Does this still occur in the most recent version?

**Comment by mikefrederick** [comment]
I tested this out in the most recent version and didn't see the issue. I can tell you are using an older version since kMFSideMenuSidebarWidth no longer exists. If you experience this in the most recent version (0.4.4) then re-open this ticket and I can investigate further.
