### ISSUE TITLE
Black screen when distributing ad hoc

### ISSUE THREAD

**Issue by marianoabdala** [mikefrederick/MFSideMenu#65]
Hi Mike, great project you've got here.

I'm having this issue where the side menu works just fine when debuging on my iPhone 4s but shows black when running it from an adhoc distribution (same device).

I really don't know where to start. Have you ever heard of anything like this?

This is how I instantiate the side menu:

```
CBYSideMenuViewController *sideMenuViewController =
(CBYSideMenuViewController *)[self.storyboard instantiateViewControllerWithIdentifier:SIDE_MENU_VIEW_CONTROLLER_ID];

self.sideMenu =
[MFSideMenu menuWithNavigationController:self.navigationController
                  leftSideMenuController:sideMenuViewController
                 rightSideMenuController:nil];

sideMenuViewController.sideMenu = self.sideMenu;
```

**Screenshots**
Debuggin from Xcode
![Debugging from Xcode](http://f.cl.ly/items/3H3O2q2M3g1V2p363V08/MFSideMenu-Debug.png)

Running adhoc
![Running adhoc](http://f.cl.ly/items/050q3d1Q391i1m3x1D3E/MFSideMenu-Adhoc.png)

Thanks in advance!

**Comment by marianoabdala** [comment]
I just managed to reproduce this in debug mode. I'm closing this issue. I might add info when I find what happened.

**Comment by dinarajas** [comment]
It occurs sometime randomly in ios 6 devices and simulators. How to get rid of this issue??

**Comment by marianoabdala** [comment]
I had some custom load code for the view controller with the side menu, that caused the issue. So I don't think it'll help you.

What you can do is check if the side menu is nil, that was what ultimately was happening to me.
