### ISSUE TITLE
Using FSideMenu with UISplitViewController

### ISSUE THREAD

**Issue by Rpaixao** [mikefrederick/MFSideMenu#66]
I added your project to my project and it works. However it appears vertically instead of horizontally in portrait mode. (Check the image on the link to understand ao it looks like)

![Captura de ecra 2013-03-28 a s 13 33 07](https://f.cloud.github.com/assets/1159505/313389/33305f56-97ac-11e2-9279-81577524747f.png)

The side menu is the blue thing. I just followed his setup. Any one knows what am i doing wrong?

**Comment by mikefrederick** [comment]
This particular issue is solved in the most recent version as it was related to a bug. That being said, if you use the split view controller in portrait mode, the SVC's gesture recognizers interfere with the MFSideMenu gestures. So if you use your SVC in portrait mode, you should disable the MFSideMenu panning when in portrait. Landscape should be okay though.
