### ISSUE TITLE
Update Size with In-Call Status Bar 

### ISSUE THREAD

**Issue by Rigter** [mikefrederick/MFSideMenu#67]
It's possible update the height from MFSideMenu programmatically?

When I show the In-Call Status Bar the left view don't resizing.

![Issue](https://f.cloud.github.com/assets/431837/330696/0bc1dc10-9bd5-11e2-92ef-15065db2e2cf.png)

I've found the delegate to detect when the status bar is resized:

```
- (void)application:(UIApplication *)application willChangeStatusBarFrame:(CGRect)newStatusBarFrame
```

But, I'dont know how resize the MFSideMenu programmatically.

Thanks.

**Comment by mikefrederick** [comment]
This issue should be fixed now. Please checkout the README for new instructions on how to utilize the library.
