### ISSUE TITLE
MFSideMenu -> MFSideMenuStateLeftMenuOpen keeps open on every view

### ISSUE THREAD

**Issue by ganidu-ashen** [mikefrederick/MFSideMenu#68]
Hi.
i have integrated the MFSideMenu in to ios app. 
At the first view . i need to keep open the side bar, so i implemented 
    [self.navigationController.sideMenu setMenuState:MFSideMenuStateLeftMenuOpen];

in to the viweDidLoad of tht class. but thr is a issue,
It has been applied to the next view. automatically the sidemenu will  open.
How can i stop this feature.??

Thanks

**Comment by mikefrederick** [comment]
You are going to have to explain your issue more clearly. What do you mean it has been "applied to the next view"? The side menu will only open when you tell it to open, and it will close when you tell it to close.

**Comment by NSDrowned** [comment]
Related question: How do you tell it to close? I tried [self.sideMenu setMenuState:MFSideMenuStateClosed] from a IBAction method but it didn't work..

**Comment by NSDrowned** [comment]
Nevermind, got it with [self.navigationController.sidemenu toggleLeftSideMenu] on the main view;
