### ISSUE TITLE
Storyboard demo update request

### ISSUE THREAD

**Issue by izaxon** [mikefrederick/MFSideMenu#69]
Hi,

Can you please update the storyboard to include a menu icon button in the toolbar?

Also, the side menu is not displayed when adding the side menu to the storyboard in my project. I try to slide on the title to the right to open the left side menu, but sliding is impossible (i.e. no movement of the view horizontally).
The only difference I have is that the navigation controller is not the storyboard initial controller. Code from AppDelegate.m:

// Initialize slide menu
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"MainStoryboard" bundle:[NSBundle mainBundle]];
    UINavigationController *navigationController = [storyboard instantiateViewControllerWithIdentifier:@"sideMenuNavigationController"];
    UIViewController *leftSideMenuViewController = [storyboard instantiateViewControllerWithIdentifier:@"leftSideMenuViewController"];
    [MFSideMenu menuWithNavigationController:navigationController
                      leftSideMenuController:leftSideMenuViewController
                     rightSideMenuController:nil];

Any help is appreciated!

Best regards,
Johan

**Comment by mikefrederick** [comment]
I will update this demo and take a look at your example.

**Comment by mikefrederick** [comment]
The storyboard demo was updated.

As for your code, are you sure that your view controllers are getting loaded correctly (i.e. none of them are nil)? How are you actually displaying your navigation controller? Can you show me the code where the navigationController becomes visible (i.e. when it is added to the window)?

**Comment by mikefrederick** [comment]
The storyboard demo has been updated to show a full configuration.
