### ISSUE TITLE
Retaining views

### ISSUE THREAD

**Issue by cannyboy** [mikefrederick/MFSideMenu#7]
How would I retain views which have already been loaded. So in the didSelectRowAtIndexPath of the SideMenuViewController it wouldn't recreate a view if the user has already seen it?

So for instance, if a map is selected in the side menu, and you zoom into New York, when you come back to that view later, it's already zoomed in.

**Comment by mikefrederick** [comment]
You would retain them like you would retain any other view (actually I think you mean retaining UIViewControllers). Set  them as a strong property somewhere and instead of creating a new instance in didSelectRowAtIndexPath just load your existing controller.

```
@property (nonatomic, strong) MyViewController *controller1;

// in didSelectRowAtIndexPath...
if(indexPath.row == 0) {
    // load controller1
}
```
