### ISSUE TITLE
Menu can be seen in the back on modal transition

### ISSUE THREAD

**Issue by NSDrowned** [mikefrederick/MFSideMenu#70]
Gonna try to explain this the best I can (English is not my strong). Let's say I have a main view that includes MSFSideMenu on the left and a navbar button on the opposite side that calls a modal view for the camera. When I'm on the main view (side menu is closed) and I click on the camera button, the vertical flip transition is shown and in the back you can see the side menu which is supposed to be closed to the left. 

How can I fix this issue (show black instead of the side menu) or did I implement the menu the wrong way?

**Comment by mikefrederick** [comment]
Can you post a screenshot?

**Comment by mikefrederick** [comment]
Going to close this issue as I can't duplicate it.
