### ISSUE TITLE
how to deselect tab bar item when a controller from side menu is clicked?

### ISSUE THREAD

**Issue by NSDSrinivas** [mikefrederick/MFSideMenu#71]
Hi,

How do i deselect tabbar item on choosing something from the left / right controller? I don't see a way of this doing this, as UITabbarcontroller is used. Can you please help me in this regard. This is not an issue, rather an enhancement.

Thanks,
Srinivas.

**Comment by mikefrederick** [comment]
You should look at [the UITabBarController reference](http://developer.apple.com/library/ios/#documentation/uikit/reference/UITabBarController_Class/Reference/Reference.html). 

In your `didSelectRowAtIndexPath:` method you could set the `selectedIndex` of your `UITabBarController` like so:
`tabBarController.selectedIndex = newIndex;`

If you have further questions on this please ask on stackoverflow.
