### ISSUE TITLE
No way to disable touch canceling on menus

### ISSUE THREAD

**Issue by jlorich** [mikefrederick/MFSideMenu#73]
I have a UITableView on the left menu I am attempting to allow re-ordering on ( (via canMoveRowAtIndexPath / moveRowAtIndexPath).  Right now when the re-order drag is initiated the PanGestureRecognizer from MFSideMenu responds to it (through shouldReceiveTouch), which by default cancels other touches and stops the reorder drag.  

It would be nice if there was a way to set cancelsTouchesInView to false for the gesture recognizer added to menuContainerView.  It seems to me the easiest way to do this would be to store the gesture recognizers in exposed properties so that this setting, and other, can be modified from outside.  It would also be possible, though less straightforward in use, to expose menuContainerView so that its gestureRecognizers property could be modified.

**Comment by mikefrederick** [comment]
You can disable panning by setting the `panMode`:

`menu.panMode = MFSideMenuPanModeNone;`

Or, if you want to keep panning enabled on your navigation controller but disable it for your side menu(s) you can do:

`menu.panMode = MFSideMenuPanModeRootViewController;`
