### ISSUE TITLE
Not detecting autorotation

### ISSUE THREAD

**Issue by dinarajas** [mikefrederick/MFSideMenu#74]
@mikefrederick 

In iOS 4.3, Integration of this repository leads to not detecting the autorotation in shouldAutorotateToInterfaceOrientation: method. 

For the first time ViewController loads, it calls the shouldAutorotateToInterfaceOrientation: method. 
After that it is not detecting the device orientations. 

But the same code works well in iOS 5 and above.

**Comment by mikefrederick** [comment]
Thanks for the info, will take a look.

**Comment by mikefrederick** [comment]
@dineshraja1990 the library recently received a large update. Can you check and see if this is still an issue? I don't have access to iOS 4.3 right now.

**Comment by dinarajas** [comment]
@mikefrederick Yes you are right. I got a update and now it's working. Sure you can close this issue. Thank you for your time.
