### ISSUE TITLE
Close menu in storyboard

### ISSUE THREAD

**Issue by mezhevikin** [mikefrederick/MFSideMenu#75]
In demo MFSideMenuDemoStoryboard on leftSideMenuViewController I add a button as CLOSE.

how to close the menu by clicking on this button?

[self.sideMenu setMenuState:MFSideMenuStateClosed]; // not working for me

**Comment by mikefrederick** [comment]
Have you assigned the sideMenu property correctly to your leftSideMenuViewController?

**Comment by mikefrederick** [comment]
I just double checked and the storyboard demo shows how to do this correctly. Your code should work correctly if your sideMenu is not nil.
