### ISSUE TITLE
Cannot load viewController using MFSidemenu

### ISSUE THREAD

**Issue by shabeermohamed** [mikefrederick/MFSideMenu#77]
I am building an app using storyboard. I am using the MFSidemenu library for creating a sidemenu like facebook app. the side menu appears properly but when i tap a cell on the side menu, the menu doesnt go away and it doesnt load another view controller. Please note that i am using storyboard.

**Comment by mikefrederick** [comment]
Please refer to the demos, they have everything you need to get up and running.

**Comment by shabeermohamed** [comment]
in your code not contain click tableview cell to change another controler

**Comment by mikefrederick** [comment]
The other demos contain that code, take a look there.

**Comment by shabeermohamed** [comment]
in story board click to another controller code not available
