### ISSUE TITLE
Menu state notification block gets called in controller even after dealloc

### ISSUE THREAD

**Issue by gtennis** [mikefrederick/MFSideMenu#78]
I have used sample code in DemoViewController.m. Therefore, I have assigned a block to listen for menu change events in viewDidLoad:
- (void)backButtonPressed:(id)sender {
  [self.navigationController popViewControllerAnimated:YES];
  }

and also set it to nil in dealloc:
- (void)viewDidLoad {
  
  ...
  self.navigationController.sideMenu.menuStateEventBlock = ^(MFSideMenuStateEvent   event) {
        switch (event) {
          ...
        }
  }
  }

However, the block gets called even after dealloc (dealloc gets called after I press back button in navigation bar). But have noticed "self.navigationController" is nil in dealloc, so setting block to nil has no use. That should be done in buttonBackPressed before popping the controller from navigationController:
- (void)backButtonPressed:(id)sender {
  
  self.navigationController.sideMenu.menuStateEventBlock = nil;
  [self.navigationController popViewControllerAnimated:YES];
  }

However, that cleans block to nil and previous controller does not get menu change events when returning back. IMHO there could be made observer style pattern code for  other controllers (that are currently on navigationController stack) to listen for menu change events.

**Comment by mikefrederick** [comment]
The block was originally implemented because it was possible to have more than one instance of MFSideMenu in your app and it would be hard to track using events. This is no longer the case. The library just received a pretty big overhaul, and events are used now.

Cheers
