### ISSUE TITLE
Gesture recognizers added to center view controller multiple times

### ISSUE THREAD

**Issue by Tylerc230** [mikefrederick/MFSideMenu#79]
Since addGestureRecognizers is called every time MFSideMenuContainerViewController.viewDidApper, gesture recognizers can be added multiple times and accumulate in the side menu's view. This is reproducible by displaying a modal view controller from the center view controller. Every time the modal is dismissed, viewDidAppear is called which adds more gesture recognizers to the menu view. This also forces the menu closed after the modal is removed. Perhaps all the code in viewDidAppear would be better suited for viewDidLoad? I'm on iOS 6 and MFSide menu v0.5.0

**Comment by mikefrederick** [comment]
Thanks for bringing this up. The code in viewDidAppear is sort of left over from the previous architecture of the library. I will take a look at what's going on in there and see what can be done.

**Comment by Tylerc230** [comment]
Cool thanks. When I move all the code in viewDidAppear to viewDidLoad and
then remove viewDidDisappear it seems to work perfectly. Great lib
otherwise.

**Comment by mikefrederick** [comment]
Yep looks good, just pushed

**Comment by Tylerc230** [comment]
Thanks!
