### ISSUE TITLE
Storyboard

### ISSUE THREAD

**Issue by RodolfoGS** [mikefrederick/MFSideMenu#8]
how can i use with storyboard?

**Comment by jweyrich** [comment]
1. Drop a `UITableViewController` in your storyboard
2. Create a new subclass of `UITableViewController`, and name it `MenuViewController`
3. Go back to the storyboard, select the new controller, then change its class to `MenuViewController`.
4. Hook up the table view's `delegate` and `dataSource` outlets to your `MenuViewController`.
5. Implement the following on your `MenuViewController`:

```
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    UIViewController *controller = nil;    
    switch (indexPath.row) {
        case 0:
            controller = [self.storyboard instantiateViewControllerWithIdentifier:@"IdOfYourViewControllerA"];
            break;
        case 1:
            controller = [self.storyboard instantiateViewControllerWithIdentifier:@"IdOfYourViewControllerB"];
            break;
        case 2:
            controller = [self.storyboard instantiateViewControllerWithIdentifier:@"IdOfYourViewControllerC"];
            break;
    }
    if (controller != nil) {
        NSArray *controllers = [NSArray arrayWithObject:controller];
        [MFSideMenuManager sharedManager].navigationController.viewControllers = controllers;
    }
    [MFSideMenuManager sharedManager].navigationController.menuState = MFSideMenuStateHidden;
}
```

That's pretty much it. If you want that _list icon_  to show up on your navigation bar, you can import `MFSideMenu.h` and call `[self setupSideMenuBarButtonItem]` on `viewDidLoad` of each `UIViewController` that is going to appear (except the `MenuViewController`).

Hope this helps.

**Comment by retrospct** [comment]
Thank you @jweyrich ! I didn't see the response until now. That worked like a charm. Cheers!

**Comment by RodolfoGS** [comment]
Thanks @jweyrich :D

**Comment by mynamespace** [comment]
I'm also trying to use MSSideMenu inside Storyboard, but I can't figure where to configure the MenuManager... That is, where should we call the following code?
Thanks!

```
MenuOptions options = MenuButtonEnabled|BackButtonEnabled;
[MFSideMenuManager configureWithNavigationController:self.navigationController sideMenuController:self menuSide:MenuRightHandSide options:options];
```

**Comment by jweyrich** [comment]
@mynamespace, this should happen in your AppDelegate. The following is what I use in my applications:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    // Override point for customization after application launch.
    UIViewController *rootViewController = [self.window rootViewController];
    UINavigationController *navigationController = (UINavigationController *)rootViewController;
    SideMenuViewController *sideMenuViewController = [[rootViewController storyboard] instantiateViewControllerWithIdentifier:@"IdOfYourMenuController"];

    // IMPORTANT: This should happen before the MFSideMenuManager is configured.
    [self.window makeKeyAndVisible];

    // Make sure to display the navigation controller before calling this
    [MFSideMenuManager configureWithNavigationController:navigationController
                                      sideMenuController:sideMenuViewController];

    return YES;
}
```

This assumes you are using an `UINavigationController` as a root view controller.

**Comment by mynamespace** [comment]
@jweyrich thank you very much :)

**Comment by Lukaz32** [comment]
What about the appDelegate? What should the code there look like?

**Comment by ddb01** [comment]
MFSideMenu is great however i can't really get my head around how to get it working with storyboard. I've implemented it without storyboard but would like very much to have it implemented so I can call different TableViews from the sideMenu. Is there anyway you could give us a demo or tutorial on how to implement it in a storyboard project, the above method you described is somehow not working for me.

**Comment by Lukaz32** [comment]
That would be just great.
