### ISSUE TITLE
How to make a fullscreen UIActionSheet on MFSideMenu?

### ISSUE THREAD

**Issue by laszlotuss** [mikefrederick/MFSideMenu#81]
Hy there,
i spend a lot of time to make this possible, but it can't figure it out.

As the title, i want a fullscreen UIActionSheet at MFSideMenu, but it always get shorted to the visible part of the sidemenu.

Also in my project it works flawless on iOS5, but not in the basic demo of MFSideMenu, while in iOS6 i always get the shorted version

Basic code:
"  UIActionSheet *action = [[UIActionSheet alloc] initWithTitle:@"Are you sure?"
                                                        delegate:self
                                               cancelButtonTitle:@"No" destructiveButtonTitle:@"Yes" otherButtonTitles: nil];
    [action showInView:self.view];
"

Thank you

![ios simulator screen shot 2013 05 09 16 39 55](https://f.cloud.github.com/assets/2952613/483247/4a0f3d42-b8b7-11e2-91df-7d1127249a50.png)

**Comment by mikefrederick** [comment]
This has nothing to do with MFSideMenu... what you are seeing is the expected behavior of UIActionSheet. UIActionSheet resizes itself to fit it's contents.
