### ISSUE TITLE
MFSideMenu stops popovers from FPPopover

### ISSUE THREAD

**Issue by hemantvikram** [mikefrederick/MFSideMenu#83]
We are using FPPopover library (https://github.com/50pixels/FPPopover) in our iOS project to display popups but for some reasons the popup are not showing up when using MFSideMenu. If we comment the following lines from the AppDelegate.m file, the FPPopover is showing up otherwise not. Can you please guide us in addressing this issue. We would like to use both these libraries in our project.
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
  {
  // some code
  …
  
  [MFSideMenu menuWithNavigationController:navigationController
                    leftSideMenuController:leftSideMenuViewController
                   rightSideMenuController:nil];

// some more code
…

```
return YES;
```

}

Thanks,
Hemant.

**Comment by mikefrederick** [comment]
Can you try moving to the most recent version of MFSideMenu? If it doesn't work on the most recent version of MFSideMenu then I would be happy to investigate.

**Comment by hemantvikram** [comment]
Thank you Mike, Problem Solved. We installed the latest lib and everything is fine now.

Thanks Again,
Hemant.

**Comment by mikefrederick** [comment]
Glad to hear it.
