### ISSUE TITLE
Changing the CenterViewController to a new one when menu is open doesn't keep the old CenterViewController offset

### ISSUE THREAD

**Issue by Francescu** [mikefrederick/MFSideMenu#86]
When the menu is open if you do a 
`setCenterViewController:[[UIViewController alloc] init]`

the new viewController will overlay the whole screen (keeping it's default frame) and the menu state won't update (Open) so the first touch will virtually close the menu..

I'm working on it (except if someone already has the solution)

**Comment by Francescu** [comment]
Ok nevermind I solved it. Should I commit and merge with my pull request or wait ?

**Comment by mikefrederick** [comment]
Can you create a separate pull request for this?

**Comment by gustly** [comment]
Qua?

On Tuesday, May 28, 2013, Michael Frederick wrote:

> Can you create a separate pull request for this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mikefrederick/MFSideMenu/issues/86#issuecomment-18546515
> .

## 

Ryan

**Comment by Francescu** [comment]
Done, you can close this issue. (a new one is open w/ pull request)
