### ISSUE TITLE
MFSideMenu support for landscape mode (ipad) 

### ISSUE THREAD

**Issue by RizITN** [mikefrederick/MFSideMenu#90]
Hi,
   I used your control in one of my app and its working fine. Now I'm working on my another app (ipad only) that works only in lanscape mode. 
I added only lanscape mode in project's plist file and the shouldAutorotateToInterfaceOrientation() function. but I'm not getting the desired results means menu should be shown by sideway not from top. (see the attached snapshot.)
![mfsideview-landscape-issue](https://f.cloud.github.com/assets/4617947/610020/74720172-cda3-11e2-8776-47cc6fb2ad47.png)

Can you please help me out what m I doing wrong? Or MFSideMenu doesn't support landscape orientation?
Following is the code to implement MFSideMenu in AppDelegate method.

 SideMenuViewController *leftSideMenuController = [[SideMenuViewController alloc] init];

```
SplashViewController *splashViewController = [[SplashViewController alloc]initWithNibName:@"SplashViewController" bundle:nil];
UINavigationController *splashNavigationController = [[UINavigationController alloc] initWithRootViewController:splashViewController];


MFSideMenuContainerViewController *container = [MFSideMenuContainerViewController
    containerWithCenterViewController:splashNavigationController
    leftMenuViewController:leftSideMenuController
    rightMenuViewController:nil];
self.window.rootViewController = container;
[self.window makeKeyAndVisible];
return YES;
```

**Comment by picolo74** [comment]
Hi, i m using a splitview too and i did not have your problem.

Do you add shouldAutoRotateToInterfaceOrientation in your UitableViewController (MasterViewController) and in the DetailViewController ? Try to return YES in both.

On your snapshot, the menu is correctly placed on the left of your splitview wich does not rotate, so the menu is not on top.

**Comment by RizITN** [comment]
Yes it was the Orientation issue, I only set key in .plist file for
landscape orientation but didn't in Master & Detail view controllers.
Anyway thanks for the response.

Regards
