### ISSUE TITLE
Show parent view instead of menu

### ISSUE THREAD

**Issue by bartender07** [mikefrederick/MFSideMenu#94]
Hi,

I am new to github and i dont know if this is the correct place to put this request.

I have an app which use this to show menu. My main view is a uitableview and when a cell is selected it shows the childview based on selection. Now in the child view when i slide right I want to show the parent view instead of the menu. is this possible?

**Comment by mikefrederick** [comment]
Do you mean that you want to show the parent view as the menu?

If so, you could do something like this:

```
container.leftMenuViewController = parentViewController;
```

I am going to close this question for now, if you need more help go ahead and ask though.
