### ISSUE TITLE
assigning custom view for pan gesture

### ISSUE THREAD

**Issue by ghost** [mikefrederick/MFSideMenu#95]
I think value would be added to this package if you had the ability to assign your own custom view (a view within the centerviewcontrollers view) for the panning of the side menus.

**Comment by mikefrederick** [comment]
Can you give an example of how this might be helpful?

**Comment by ghost** [comment]
Id like to add small bumpers in the center view to pan the side menus like the google maps app.

**Comment by chourobin** [comment]
I see this being helpful if we want to allow panning on certain elements (i.e. UINavigationBar).
