### ISSUE TITLE
Gap between center view controller and right side menu and no shadow

### ISSUE THREAD

**Issue by twestley** [mikefrederick/MFSideMenu#97]
With latest version of MFSideMenu (downloaded today), there is a gap between the right edge of the center view controller and the left edge of the right side menu and no shadow with MFSideMenuDemoBasic (and my app).

This is not new. Older versions do this as well.

iPad 3 in Landscape, iOS 6.1.3. Simulator is OK. Built with Xcode 4.6.

Simulator right side menu view frame is {{754, 0}, {270, 748}}. Device is {{774, 0}, {270, 748}}.

![mfsidemenugap](https://f.cloud.github.com/assets/1317260/785866/bbcb1c60-ea91-11e2-9fe6-28cfd96b556d.PNG)

**Comment by mikefrederick** [comment]
Thanks, I will take a look
