### ISSUE TITLE
MFSideMenu Over MasterView of UISplitViewController

### ISSUE THREAD

**Issue by RizITN** [mikefrederick/MFSideMenu#98]
I want to know that is it possible to slide Left side menu over the ContainerViewController without sliding/ moving the ContainerViewController from its position. 

Actually I've a scenario. I used the MFSideMenu for my iPad app (landscape only) along the UISplitViewController. The client's requirement is that he wants to slide the left side menu on the MasterViewController, the DetailViewController should not move from its position. 

Means when we slide  or click on the Menu button placed on the DetailViewController's navigation bar, the menu should slide from left to whole over the MasterViewController, DetailViewController shouldn't move from its position.

I'll be very thankful if you solve the issue

Regards

**Comment by mikefrederick** [comment]
MFSideMenu doesn't support this functionality, nor will it in the foreseeable future. Sorry.
